name: Upload Glossary Terms to Purview

on:
  workflow_dispatch:

jobs:
  upload-glossary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-identity requests

    - name: Run glossary upload script
      env:
        AZURE_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        AZURE_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        AZURE_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
        PURVIEW_NAME: banupurview
        GLOSSARY_NAME: Enterprise Business Glossary
      run: python glossary_upload.py
